name: Link Checker

on:
  schedule:
    - cron: "0 0 * * 0" # Todos los domingos a medianoche
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress './README.md' './src/**/*.astro' './src/**/*.ts'
          fail: true
